title: "Kaleem Clarkson"
baseline: "Coming Soon"
description: "Personal website - launching soon!"
baseurl: /
url: https://www.kaleemclarkson.com
destination: docs
theme:
  - comingsoon
comingsoon:
  subscribe:
    placeholder: "Enter your email..."
    button: "Notify Me!"
assets:
  remote:
    enabled: false
  compile:
    variables:
      primary: '#69B7FF'
      secondary: '#69C748'
social:
  twitter:
    site: YourTwitter
  github:
    username: kaleemclarkson
